version: "3.9"

volumes:
  pg_volume:

services:
  eureka-server:
    build: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
        EUREKA_URL: http://eureka-server:8761/eureka
  api-gateway:
      build: api-gateway
      restart: always
      container_name: api-gateway
      ports:
        - "8081:8081"
      depends_on:
          - eureka-server
      environment:
          JWT_SECRET: anuidisudagovnosobachyetireshilkomneleztubludokvonychiy
          EUREKA_URL: http://eureka-server:8761/eureka

  config-server:
      build: config-server
      restart: always
      container_name: config-server
      ports:
          - "8888:8888"
      depends_on:
          - eureka-server
      environment:
          EUREKA_URL: http://eureka-server:8761/eureka

  hotdogs-client:
    build: hotdogs-client
    restart: always
    container_name: dog-service
#    ports:
#      - "8080:8080"
    depends_on:
      - postgresql_database
      - eureka-server
    environment:
        POSTGRES_URL: jdbc:postgresql://postgresql_database:5432/postgres
        POSTGRES_USERNAME: postgres
        POSTGRES_PASSWORD: postgres
        JWT_SECRET: anuidisudagovnosobachyetireshilkomneleztubludokvonychiy
        EUREKA_URL: http://eureka-server:8761/eureka
        CONFIG_SERVER_URL: http://config-server:8888
    #          CONFIG_SERVER_URL: ${CONFIG_URL}

  owner-service:
      build: owner-service
      restart: always
      container_name: owner-service
      depends_on:
          - postgresql_database
          - eureka-server
      environment:
          POSTGRES_URL: jdbc:postgresql://postgresql_database:5432/postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          JWT_SECRET: anuidisudagovnosobachyetireshilkomneleztubludokvonychiy
          EUREKA_URL: http://eureka-server:8761/eureka
          CONFIG_SERVER_URL: http://config-server:8888
    #          CONFIG_SERVER_URL: ${CONFIG_URL}
  file-service:
      build: file-service
      restart: always
      container_name: file-service
      depends_on:
          - postgresql_database
          - eureka-server
      environment:
          POSTGRES_URL: jdbc:postgresql://postgresql_database:5432/postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          JWT_SECRET: anuidisudagovnosobachyetireshilkomneleztubludokvonychiy
          EUREKA_URL: http://eureka-server:8761/eureka
          CONFIG_SERVER_URL: http://config-server:8888
#          CONFIG_SERVER_URL: ${CONFIG_URL}

  user-service:
      build: user-service
      restart: always
      container_name: user-service
      depends_on:
          - postgresql_database
          - eureka-server
      environment:
          POSTGRES_URL: r2dbc:postgresql://postgres:postgres@host.docker.internal:5432/postgres
#          POSTGRES_URL: r2dbc:postgresql://postgresql_database:5432/postgres
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          JWT_SECRET: anuidisudagovnosobachyetireshilkomneleztubludokvonychiy
          JWT_LIFETIME: PT30M
          EUREKA_URL: http://eureka-server:8761/eureka
          CONFIG_SERVER_URL: http://config-server:8888

  postgresql_database:
    image: postgis/postgis:15-3.4
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
