version: "3.9"

volumes:
  pg_volume:

services:

  java_application:
    build: .
    restart: always
    container_name: hotdogs
    ports:
      - "8080:8080"
    depends_on:
      - postgresql_database
    environment:
      POSTGRES_URL: jdbc:postgresql://postgresql_database:5432/postgres
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFETIME: ${JWT_LIFETIME}


  postgresql_database:
    image: postgis/postgis:15-3.4
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
