name: run tests

on:
    pull_request:
        branches: [ "master" ]

jobs:
    test:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: 'corretto'
                  java-version: '17'
                  cache: 'gradle'
                  cache-dependency-path: | # optional
                      api-gateway/*.gradle*
                      config-server/*.gradle*
                      eureka-server/*.gradle*
                      file-service/*.gradle*
                      hotdogs-client/*.gradle*
                      notification-service/*.gradle*
                      owner-service/*.gradle*
                      user-service/*.gradle*
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew test